### ISSUE TITLE
_add_custom_params() takes 4 positional arguments but 5 were given

### ISSUE THREAD

**Issue by peterk** [webrecorder/webrecorder#564] opened 2018-06-30 14:26 UTC
Set up the latest version from today and started it with docker-compose. Registered a user, logged in, but every time I try to record a page I get the following error in the log.

Client is (native) Safari but happens when I try Chrome as well.

```
app_1         | [pid: 10|app: 0|req: 1/20] 10.0.1.41 () {46 vars in 996 bytes} [Sat Jun 30 14:21:51 2018] GET /_new/default-collection/DN/record/mp_/https://www.dn.se/ => generated 0 bytes in 12 msecs (HTTP/1.1 303) 3 headers in 176 bytes (2 switches on core 399)
app_1         | Traceback (most recent call last):
app_1         |   File "/usr/local/lib/python3.5/site-packages/bottle.py", line 862, in _handle
app_1         |     return route.call(**args)
app_1         |   File "/usr/local/lib/python3.5/site-packages/bottle.py", line 1740, in wrapper
app_1         |     rv = callback(*a, **ka)
app_1         |   File "./webrecorder/contentcontroller.py", line 203, in do_record
app_1         |     return self.handle_routing(wb_url, user, coll, rec, type='record', redir_route='record')
app_1         |   File "./webrecorder/contentcontroller.py", line 554, in handle_routing
app_1         |     resp = self.render_content(wb_url, kwargs, request.environ)
app_1         |   File "/usr/local/lib/python3.5/site-packages/pywb-2.0.4-py3.5.egg/pywb/apps/rewriterapp.py", line 348, in render_content
app_1         |     self._add_custom_params(cdx, r.headers, kwargs, record)
app_1         | TypeError: _add_custom_params() takes 4 positional arguments but 5 were given
```

**Comment by ikreymer** [comment] 2018-07-06 01:05
Should be fixed now, sorry about that. We have it fixed on `develop` branch, which includes a major update, but now also patched on `master` as well. (Was caused by an incompatible change in pywb 2.0.4)

**Closed** 2018-07-06 01:04 UTC
